animations {
  enabled = true

  bezier = bounce, 0.0, 1.25, 0.15, 1.0
  bezier = buttery, 0.1, 1.15, 0.15, 1.02
  bezier = smooth, 0.0, 0.0, 0.12, 1.0
  bezier = linear, 0.0, 0.0, 1.0, 1.0

  animation = windowsIn, 1, 4.5, bounce, slide
  animation = windowsOut, 1, 3.5, smooth, slide
  animation = windowsMove, 1, 4, buttery, slide
  
  animation = fadeIn, 1, 3.5, smooth
  animation = fadeOut, 1, 3, smooth
  animation = fadeDim, 1, 4, smooth
  animation = fadeShadow, 1, 4, smooth

  animation = workspaces, 1, 4.5, buttery, slidefade 10%
  animation = specialWorkspace, 1, 4.5, buttery, slidefadevert -15%

  animation = border, 1, 7, smooth
  animation = borderangle, 1, 35, linear, loop

  animation = layersIn, 1, 4, bounce, slide
  animation = layersOut, 1, 3, smooth, slide
}
