windowrule {
  name = discord
  workspace = special:discord
  match:class = ^(discord)$
}

windowrule {
  name = spotify
  workspace = special:music
  match:class = ^(spotify)$
}

# Fix some dragging issues with xwayland
windowrule {
  name = fix-xwayland-drag
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}
